name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        std: [20, 23]
        cxx: [g++-10, g++-11, g++-12, g++-13, g++-14, g++-14, clang++-10, clang++-11, clang++-12, clang++-13, clang++-14, clang++-15, clang++-16, clang++-17, clang++-18, clang++-19]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Toolchain
      run: |
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ focal main'
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ focal universe' 
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ jammy main'
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ jammy universe' 
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ noble main'
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ noble universe'   
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

        sudo apt update
        CXX=${{matrix.cxx}}
        sudo apt install ${CXX/"clang++"/"clang"} # substitutes inline clang++ by clang because clang++ cannot be seldom installed

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=${{matrix.std}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target test